const TYPES = {
  Server: Symbol.for('Server'),
  RouterHttp: Symbol.for('RouterHttp'),
  UserRouter: Symbol.for('UserRouter'),
  UserController: Symbol.for('UserController'),
  UserServices: Symbol.for('UserService'),
  PasskeyService: Symbol.for('PasskeyService'),
  PasskeyController: Symbol.for('PasskeyController'),
  PasskeyRouter: Symbol.for('PasskeyRouter'),
  SubscriptionController: Symbol.for('SubscriptionController'),
  SubscriptionService: Symbol.for('SubscriptionService'),
  RestClientService: Symbol.for('RestClientService'),
  StorageService: Symbol.for('StorageService'),
  S3Service: Symbol.for('S3Service'),
  LibraryService: Symbol.for('LibraryService'),
  LibraryController: Symbol.for('LibraryController'),
  LibraryRouter: Symbol.for('LibraryRouter'),
  CacheService: Symbol.for('CacheService'),
  SubscriptionMiddleware: Symbol.for('SubscriptionMiddleware'),
  UserAdminMiddleware: Symbol.for('UserAdminMiddleware'),
  LoggerService: Symbol.for('LoggerService'),
  AdminService: Symbol.for('AdminService'),
  AdminController: Symbol.for('AdminController'),
  AdminRouter: Symbol.for('AdminRouter'),
  StorageController: Symbol.for('StorageController'),
  StorageRouter: Symbol.for('StorageRouter'),
  VersionMiddleware: Symbol.for('VersionMiddleware'),
  EmailService: Symbol.for('EmailService'),
  EmailVerificationService: Symbol.for('EmailVerificationService'),
  RetentionMessagingService: Symbol.for('RetentionMessagingService'),
  RetentionMessagingController: Symbol.for('RetentionMessagingController'),
  RetentionMessagingRouter: Symbol.for('RetentionMessagingRouter'),
};

export { TYPES };
